name: Docker Image Build and Push to Docker Hub

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username YOURUSERNAME --password-stdin
        docker build . --file Dockerfile --tag YOURUSERNAME/IMAGENAME:latest
        docker push YOURUSERNAME/IMAGENAME:latest
        GIT_SHA="$(git rev-parse --short HEAD)"
        docker tag YOURUSERNAME/IMAGENAME:latest YOURUSERNAME/IMAGENAME:$GIT_SHA
        docker push YOURUSERNAME/IMAGENAME:$GIT_SHA
