name: Test with testthat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  testthat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
    - name: Test with testthat
      run: |
        R --file=tests/testthat.R⁠
